// fetch actions
export const REQUEST_COURSE_SEARCH = 'REQUEST_COURSE_SEARCH';
export const RECEIVE_COURSE_SEARCH = 'RECEIVE_COURSE_SEARCH';
export const REQUEST_TIMETABLE_SEARCH = 'REQUEST_TIMETABLE_SEARCH';
export const RECEIVE_TIMETABLE_SEARCH = 'RECEIVE_TIMETABLE_SEARCH';
export const REQUEST_BUILDER_SEARCH = 'REQUEST_BUILDER_SEARCH';
export const RECEIVE_BUILDER_SEARCH = 'RECEIVE_BUILDER_SEARCH';

// schedule actions
export const ADD_TO_SCHEDULE = 'ADD_TO_SCHEDULE';
export const RESET_SCHEDULE = 'RESET_SCHEDULE';
export const REMOVE_COURSE = 'REMOVE_COURSE';

// generator actions
export const START_GENERATING = 'START_GENERATING';
export const END_GENERATING = 'END_GENERATING';
export const FILTERED_COURSES = 'FILTERED_COURSES';
export const START_REDIRECT = 'START_REDIRECT';
export const END_REDIRECT = 'END_REDIRECT';

// builder actions
export const ADD_TO_BUILDER = 'ADD_TO_BUILDER';
export const REMOVE_FROM_BUILDER = 'REMOVE_FROM_BUILDER';
export const SELECT_CRN = 'SELECT_CRN';
export const UNSELECT_CRN = 'UNSELECT_CRN';
export const RESET_BUILDER = 'RESET_BUILDER';
